[project]
name = "mh0386.backend.io"
version = "0.1.0"
description = "Backend Part of my website"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.112.2",
    "uvicorn>=0.30.6",
]
