name: info
on:
    schedule:
        - cron: "0 0 * * *"
    push:
        branches:
            - main
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              uses: upciti/wakemeops-action@v1
              with:
                  packages: jq
            - name: Update info.json
              run: |
                  value=$(curl -s "https://mh0386backend.vercel.app/get_views" | jq -r '.views')
                  echo "{\"views\": $value}" | jq --indent 4 '.' > data/info.json
            - name: Commit and push
              continue-on-error: true
              run: |
                git config --global user.email "action@github.com"
                git config --global user.name "GitHub Action"
                git add data/info.json
                git commit -m "Update info.json"
                git pull
                git push