name: UV
on: [push]
jobs:
  uv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Cache
        uses: actions/cache@v4.1.1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Minimize uv cache
        run: |
          pip install -U uv
          uv cache prune --ci
      - name: Sync project dependencies
        run: uv sync
      - name: Export pyproject.toml to requirements.txt
        run: uv export > requirements.txt
      - name: Commit and Push new file
        run: |
          git config --global user.email "mohamed.hisham.abdelzaher@gmail.com"
          git config --global user.name "Mohamed Hisham Abdelzaher"
          git add requirements.txt
          git commit -m "Update requirements file"
          git pull
          git push
        continue-on-error: true
